'use client';
import {bindReactionGesture} from '../reactions.js';
export {openReactionPicker,reactionEmoji,type ReactionPickerOptions} from '../reactions.js';
import {forwardRef,useEffect,useId,useRef,useState,type ReactNode,type HTMLAttributes,type ButtonHTMLAttributes,type InputHTMLAttributes} from 'react';
import {resizeComposer,observeComposer} from '../composer-size.js';
import {rsvpOptions,type ThemeMode,type Accent,type Density,type Conversation,type Person,type Rsvp} from '../tokens.js';
export type {ThemeMode,Accent,Density,Conversation,Person,Rsvp} from '../tokens.js';
const cx=(...parts:(string|undefined|false)[])=>parts.filter(Boolean).join(' ');
export interface ThemeProps extends HTMLAttributes<HTMLDivElement>{mode?:ThemeMode;accent?:Accent;density?:Density}
export function Theme({mode='system',accent='citron',density='comfortable',className,...props}:ThemeProps){return <div {...props} className={cx('sp-theme',className)} data-theme={mode} data-accent={accent} data-density={density}/>}
export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement>{variant?:'primary'|'secondary'|'quiet'|'danger';busy?:boolean}
export const Button=forwardRef<HTMLButtonElement,ButtonProps>(function Button({variant='secondary',busy=false,disabled,className,children,...props},ref){return <button type="button" {...props} ref={ref} className={cx('sp-button',className)} data-variant={variant} disabled={disabled||busy} aria-busy={busy||undefined}>{children}</button>});
export interface TextFieldProps extends InputHTMLAttributes<HTMLInputElement>{label:string;hint?:string;error?:string}
export const TextField=forwardRef<HTMLInputElement,TextFieldProps>(function TextField({label,hint,error,id,className,...props},ref){const uid=useId();const inputId=id||uid;return <div className="sp-field"><label className="sp-label" htmlFor={inputId}>{label}</label><input {...props} ref={ref} id={inputId} className={cx('sp-input',className)} aria-invalid={!!error||undefined} aria-describedby={cx(props['aria-describedby'],(error||hint)?inputId+'-help':undefined)||undefined}/>{(error||hint)&&<p id={inputId+'-help'} className={cx('sp-help',!!error&&'sp-error')} role={error?'alert':undefined}>{error||hint}</p>}</div>});
export interface AppShellProps {header:ReactNode;navigation:ReactNode;children:ReactNode;view?:'list'|'detail';navigationLabel?:string}
export function AppShell({header,navigation,children,view='detail',navigationLabel='Samtalar'}:AppShellProps){return <div className="sp-shell" data-view={view}><header className="sp-masthead">{header}</header><div className="sp-workspace"><nav className="sp-sidebar" aria-label={navigationLabel}>{navigation}</nav><main className="sp-main">{children}</main></div></div>}
export interface ConversationListProps {items:Conversation[];selectedId:string;onSelect:(id:string)=>void;emptyLabel?:string}
export function ConversationList({items,selectedId,onSelect,emptyLabel='Ingen samtalar funne.'}:ConversationListProps){const groups=Array.from(new Set(items.map(c=>c.group)));return <div className="sp-conversations">{!items.length&&<p className="sp-empty" role="status">{emptyLabel}</p>}{groups.map(group=><section key={group}><h2 className="sp-group-label sp-kicker">{group}</h2>{items.filter(c=>c.group===group).map(c=><button type="button" key={c.id} className="sp-conversation" aria-current={c.id===selectedId?'page':undefined} onClick={()=>onSelect(c.id)}><span className="sp-conversation-name">{c.name}</span>{c.muted&&<span className="sp-help" aria-label="Varsel av">○</span>}{!!c.unread&&<span className="sp-badge" aria-label={`${c.unread} uleste`}>{c.unread}</span>}</button>)}</section>)}</div>}
export interface MessageProps {onReactionRequest?:(anchor:HTMLElement)=>void;author:string;authorContent?:ReactNode;time:string;dateTime?:string;children:ReactNode;actions?:ReactNode;status?:string}
export function Message({author,authorContent,time,dateTime,children,actions,status,onReactionRequest}:MessageProps){const element=useRef<HTMLElement>(null);useEffect(()=>element.current&&onReactionRequest?bindReactionGesture(element.current,onReactionRequest):undefined,[onReactionRequest]);return <article ref={element} className="sp-message"><header className="sp-message-meta">{authorContent ?? <strong>{author}</strong>}<time className="sp-time" dateTime={dateTime}>{time}</time>{status&&<span className="sp-help">{status}</span>}</header><div className="sp-message-body">{children}</div>{actions&&<footer className="sp-message-actions">{actions}</footer>}</article>}
export interface ComposerProps {value:string;onChange:(value:string)=>void;onSend:(value:string)=>void;label:string;placeholder?:string;sendLabel?:string;hint?:string;disabled?:boolean;busy?:boolean;error?:string;leading?:ReactNode;tools?:ReactNode;toolsLabel?:string;sendOnEnter?:boolean}
export function Composer({value,onChange,onSend,label,placeholder='Skriv ei melding …',sendLabel='Send ↑',hint='Ctrl/⌘ + Enter for å sende',disabled=false,busy=false,error,leading,tools,toolsLabel='Skriveverktøy',sendOnEnter=false}:ComposerProps){const id=useId();const [toolsOpen,setToolsOpen]=useState(!!value);const field=useRef<HTMLTextAreaElement>(null);useEffect(()=>{if(field.current)resizeComposer(field.current);},[value]);useEffect(()=>field.current?observeComposer(field.current):undefined,[]);const submit=()=>{if(value.trim()&&!disabled&&!busy)onSend(value.trim());};return <form className="sp-composer" onFocus={e=>{if(e.target instanceof HTMLTextAreaElement)setToolsOpen(true);}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node)&&!value.trim())setToolsOpen(false);}} onSubmit={e=>{e.preventDefault();submit();}}>{leading}<label className="sp-label" htmlFor={id}>{label}</label><textarea ref={field} rows={1} id={id} className="sp-textarea" value={value} onChange={e=>{setToolsOpen(true);onChange(e.target.value);}} placeholder={placeholder} disabled={disabled||busy} aria-describedby={id+'-help'} aria-invalid={!!error||undefined} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing&&((e.ctrlKey||e.metaKey)||(sendOnEnter&&!e.shiftKey))){e.preventDefault();submit();}}}/><div className="sp-composer-footer"><span id={id+'-help'} className={cx('sp-help',!!error&&'sp-error')} role={error?'alert':undefined}>{error||hint}</span><>{tools&&<Button variant="quiet" aria-label={toolsLabel} title={toolsLabel} aria-controls={id+'-tools'} aria-expanded={toolsOpen} onClick={()=>setToolsOpen(!toolsOpen)}>＋</Button>}<Button variant="primary" type="submit" disabled={disabled||!value.trim()} busy={busy}>{busy?'Sender …':sendLabel}</Button></></div>{tools&&<div id={id+'-tools'} className="sp-composer-tools" hidden={!toolsOpen}>{tools}</div>}</form>}
export interface EventCardProps {title:string;when:string;where?:string;value?:Rsvp;onChange:(value:Rsvp)=>void;summary?:string;label?:string;options?:ReadonlyArray<{value:Rsvp;label:string}>;disabled?:boolean}
export function EventCard({title,when,where,value,onChange,summary,label='Invitasjon',options=rsvpOptions,disabled=false}:EventCardProps){const id=useId();return <section className="sp-event" aria-labelledby={id}><span className="sp-kicker sp-event-tag">{label}</span><h3 id={id}>{title}</h3><div className="sp-event-details">{when}{where&&<><br/>{where}</>}</div><div className="sp-rsvp" role="group" aria-label={label}>{options.map(o=><label key={o.value} className="sp-radio"><input type="radio" name={id} value={o.value} checked={value===o.value} disabled={disabled} onChange={()=>onChange(o.value)}/>{o.label}</label>)}</div>{summary&&<p className="sp-help" role="status">{summary}</p>}</section>}
export function Avatar({name}: {name:string}){return <span className="sp-avatar" aria-hidden="true">{name.trim().split(/\s+/).slice(0,2).map(w=>Array.from(w)[0]).join('').toLocaleUpperCase()}</span>}
export interface PersonListProps {people:Person[];actions?:(person:Person)=>ReactNode;emptyLabel?:string}
export function PersonList({people,actions,emptyLabel='Ingen personar funne.'}:PersonListProps){return people.length?<ul className="sp-person-list">{people.map(p=><li className="sp-person" key={p.id}><Avatar name={p.name}/><div className="sp-person-info">{p.name}{p.detail&&<small>{p.detail}</small>}</div>{actions?.(p)}</li>)}</ul>:<p className="sp-empty" role="status">{emptyLabel}</p>}
export interface DialogProps {open:boolean;onClose:()=>void;title:string;children:ReactNode;closeLabel?:string}
export function Dialog({open,onClose,title,children,closeLabel='Lukk'}:DialogProps){const ref=useRef<HTMLDialogElement>(null);const id=useId();useEffect(()=>{const el=ref.current;if(!el)return;if(open&&!el.open)el.showModal();if(!open&&el.open)el.close();},[open]);return <dialog className="sp-dialog" ref={ref} aria-labelledby={id} onCancel={e=>{e.preventDefault();onClose();}} onClose={()=>{if(open)onClose();}}><header className="sp-dialog-head"><h2 id={id}>{title}</h2><Button onClick={onClose} aria-label={closeLabel}>{closeLabel} ×</Button></header><div className="sp-dialog-body">{children}</div></dialog>}
export function Status({children,tone='info'}:{children:ReactNode;tone?:'info'|'error'}){return <div className="sp-status" data-tone={tone} role={tone==='error'?'alert':'status'}>{children}</div>}
export interface ThreadPaneProps {title?:string;context?:string;parent:ReactNode;children:ReactNode;composer:ReactNode;onClose:()=>void;closeLabel?:string}
export function ThreadPane({title='Tråd',context,parent,children,composer,onClose,closeLabel='Til samtalen'}:ThreadPaneProps){const id=useId();return <section className="sp-thread-pane" aria-labelledby={id} onKeyDown={e=>{if(e.key==='Escape'&&!e.defaultPrevented){e.stopPropagation();onClose();}}}><header className="sp-context"><div><div className="sp-kicker">{context}</div><h2 id={id} className="sp-heading">{title}</h2></div><Button onClick={onClose} aria-label={closeLabel}>← {closeLabel}</Button></header><div className="sp-thread-replies"><div className="sp-thread-parent">{parent}</div>{children}</div>{composer}</section>}
