import {useState,useSyncExternalStore,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Theme,Button,TextField,AppShell,ConversationList,Message,Composer,EventCard,PersonList,Dialog,ThreadPane,openReactionPicker} from '../src/react/index';
import '../src/styles.css';import './shared/demo.css';
import {getState,subscribe,update,select,draft,send,react,retry,reply,createConversation,attach,rsvpSummary,closeThread,threadDraft,sendThread} from './shared/model';
function App(){const s=useSyncExternalStore(subscribe,getState,getState);const [name,setName]=useState('');const [error,setError]=useState('');const file=useRef<HTMLInputElement>(null);const timeline=useRef<HTMLDivElement>(null);const nearBottom=useRef(true);const room=s.conversations.find(c=>c.id===s.selected)||s.conversations[0];const allMessages=s.messages[room.id]||[];const messages=allMessages.filter(m=>!m.parentId);const parent=allMessages.find(m=>m.id===s.threadId);const threadMessages=parent?allMessages.filter(m=>m.parentId===parent.id):[];
useEffect(()=>{if(timeline.current&&(nearBottom.current||messages.at(-1)?.author==='Du'))timeline.current.scrollTop=timeline.current.scrollHeight;},[room.id,messages.length]);
const picker=(id:string,anchor:HTMLElement)=>{const m=allMessages.find(m=>m.id===id);openReactionPicker(anchor,{selected:m?.reaction?(m.emoji||'❤️'):undefined,onSelect:emoji=>react(id,emoji)});};
const choose=(id:string)=>{nearBottom.current=true;select(id);};
return <Theme mode={s.theme} className="demo-root" data-compact={s.compact}>
 <div className="demo-toolbar"><div className="demo-tools"><a href="./index.html" aria-current="page">React</a><a href="./vue.html">Vue</a><span className="demo-local">Lokal demo</span></div><div className="demo-tools"><Button aria-label="Byt fargetema" onClick={()=>update({theme:s.theme==='dark'?'light':'dark'})}>{s.theme==='dark'?'Lyst':'Mørkt'}</Button><Button aria-label="Smal førehandsvising" aria-pressed={s.compact} onClick={()=>update({compact:!s.compact})}>{s.compact?'Full breidd':'Vis smal'}</Button></div></div>
 <div className="demo-surface"><AppShell view={s.view} header={<><span className="sp-brand">Sprøyt.</span><span className="demo-local">Berre i nettlesaren din</span></>} navigation={<><TextField label="Finn ein samtale" type="search" value={s.query} onChange={e=>update({query:e.target.value})} placeholder="Søk etter namn …"/><ConversationList items={s.conversations.filter(c=>(c.name+' '+c.group).toLocaleLowerCase().includes(s.query.toLocaleLowerCase()))} selectedId={room.id} onSelect={choose}/><Button className="demo-new" onClick={()=>{setName('');setError('');update({dialog:'new'});}}>+ Ny samtale</Button></>}>
 <div className="sp-discussion" data-thread-open={!!parent}><section className="sp-channel-pane" aria-label="Samtale">
 <header className="sp-context"><div><div className="sp-kicker">{room.group}</div><h1 className="sp-heading">{room.name}</h1></div><div className="sp-row"><Button className="sp-only-compact" onClick={()=>update({view:'list'})}>← Samtalar</Button><Button onClick={()=>update({dialog:'people',personQuery:''})}>Folk · {s.people.length}</Button></div></header>
 <div className="sp-timeline" ref={timeline} onScroll={e=>{const el=e.currentTarget;nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<80;}}><div className="sp-date sp-kicker">Samtalen</div>{!messages.length&&<div className="demo-empty"><h2 className="sp-heading">Her byrjar samtalen.</h2><p>Skriv den første meldinga nedanfor.</p></div>}{messages.map(m=><Message key={m.id} onReactionRequest={anchor=>picker(m.id,anchor)} author={m.author} time={m.time} status={m.status==='failed'?'Ikkje send':undefined} actions={<><Button variant="quiet" aria-pressed={m.reaction} aria-label={`Reager på meldinga frå ${m.author}`} onClick={e=>picker(m.id,e.currentTarget)}>{m.reaction?(m.emoji||'❤️')+' 1':'♡'}</Button><Button variant="quiet" onClick={()=>reply(m)}>Svar</Button>{m.status==='failed'&&<Button variant="danger" onClick={()=>retry(m.id)}>Prøv igjen</Button>}</>}>{m.reply&&<div className="demo-reply">{m.reply}</div>}{m.body}{m.image&&<button type="button" className="demo-image-button" aria-label="Opne bilete" onClick={()=>update({dialog:'image',image:m.image!})}><img className="demo-image" src={m.image} alt={m.imageName||'Vedlagt bilete'}/></button>}{m.event&&<EventCard title="Middag på laurdag" when="19. september · 18:00" where="Hos Anne" value={s.rsvp} onChange={rsvp=>update({rsvp})} summary={rsvpSummary(s.rsvp)}/>}{allMessages.some(r=>r.parentId===m.id)&&<button type="button" className="sp-thread-link" aria-expanded={s.threadId===m.id} onClick={()=>reply(m)}>{allMessages.filter(r=>r.parentId===m.id).length} svar · Opne tråd →</button>}</Message>)}</div>
 <div className="demo-notice" role="status">{s.notice}</div>
 <Composer label={`Melding til ${room.name}`} value={s.drafts[room.id]||''} onChange={draft} onSend={send} tools={<div className="demo-attachment"><Button variant="quiet" onClick={()=>file.current?.click()}>+ Bilete</Button><label className="demo-check"><input type="checkbox" checked={s.failNext} onChange={e=>update({failNext:e.target.checked})}/>Test sendefeil</label></div>} leading={<>{s.replies[room.id]&&<div className="demo-reply"><span>{s.replies[room.id]}</span><Button variant="quiet" aria-label="Avbryt svar" onClick={()=>update({replies:{...s.replies,[room.id]:''}})}>×</Button></div>}{s.images[room.id]?.data&&<div className="demo-attachment"><span>{s.images[room.id].name}</span><Button variant="quiet" onClick={()=>update({images:{...s.images,[room.id]:{data:'',name:''}}})}>Fjern</Button></div>}</>}/>
 <input className="demo-file" aria-label="Vel bilete" ref={file} type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{attach(e.target.files?.[0]);e.target.value='';}}/>
 </section>{parent&&<ThreadPane key={parent.id} context={room.name} title="Tråd" onClose={closeThread} parent={<Message author={parent.author} time={parent.time}>{parent.body}{parent.event&&<p className="sp-help">Invitasjon · Middag på laurdag</p>}{parent.image&&<img className="demo-image" src={parent.image} alt={parent.imageName||'Vedlagt bilete'}/>}</Message>} composer={<Composer label={`Svar i tråd til ${parent.author}`} placeholder="Svar i denne tråden …" value={s.threadDrafts[parent.id]||''} onChange={threadDraft} onSend={sendThread}/>}>
 <div className="sp-date sp-kicker" role="status">{threadMessages.length} svar</div>{!threadMessages.length&&<p className="sp-help">Svar her blir samla under denne meldinga.</p>}{threadMessages.map(m=><Message key={m.id} onReactionRequest={anchor=>picker(m.id,anchor)} author={m.author} time={m.time} actions={<Button variant="quiet" aria-pressed={m.reaction} aria-label={`Reager på svaret frå ${m.author}`} onClick={e=>picker(m.id,e.currentTarget)}>{m.reaction?(m.emoji||'❤️')+' 1':'♡'}</Button>}>{m.body}</Message>)}
 </ThreadPane>}</div></AppShell></div>
 <Dialog open={s.dialog==='people'} title={`Folk i ${room.name}`} onClose={()=>update({dialog:null})}><TextField label="Finn ein person" type="search" value={s.personQuery} onChange={e=>update({personQuery:e.target.value})}/><PersonList people={s.people.filter(p=>p.name.toLocaleLowerCase().includes(s.personQuery.toLocaleLowerCase()))}/><p className="demo-caption">Illustrerande deltakarar. Demoen inviterer ingen.</p></Dialog>
 <Dialog open={s.dialog==='new'} title="Ny samtale" onClose={()=>update({dialog:null})}><form className="sp-stack" onSubmit={e=>{e.preventDefault();if(!name.trim()){setError('Skriv eit namn.');return;}if(!createConversation(name))setError('Du har allereie ein samtale med dette namnet.');}}><TextField label="Namn på samtalen" value={name} onChange={e=>{setName(e.target.value);setError('');}} error={error} maxLength={80} autoComplete="off"/><Button type="submit" variant="primary">Opprett samtale</Button></form></Dialog>
 <Dialog open={s.dialog==='image'} title="Bilete" onClose={()=>update({dialog:null})}>{s.image&&<img className="demo-image-full" src={s.image} alt="Vedlagt bilete i full storleik"/>}</Dialog>
 </Theme>;
}
createRoot(document.getElementById('root')!).render(<App/>);
