import {createApp,defineComponent,h,shallowRef,onUnmounted,ref,watch,nextTick} from 'vue';
import {Theme,Button,TextField,AppShell,ConversationList,Message,Composer,EventCard,PersonList,Dialog,ThreadPane,openReactionPicker} from '../src/vue/index';
import '../src/styles.css';import './shared/demo.css';
import {getState,subscribe,update,select,draft,send,react,retry,reply,createConversation,attach,rsvpSummary,closeThread,threadDraft,sendThread} from './shared/model';
import type {Rsvp} from '../src/tokens';
createApp(defineComponent({setup(){const state=shallowRef(getState());const stop=subscribe(()=>state.value=getState());onUnmounted(stop);const name=ref('');const error=ref('');const file=ref<HTMLInputElement>();const timeline=ref<HTMLDivElement>();let nearBottom=true;
watch([()=>state.value.selected,()=>(state.value.messages[state.value.selected]||[]).filter(m=>!m.parentId).length],async()=>{await nextTick();if(timeline.value&&(nearBottom||(state.value.messages[state.value.selected]||[]).filter(m=>!m.parentId).at(-1)?.author==='Du'))timeline.value.scrollTop=timeline.value.scrollHeight;},{immediate:true});
const picker=(id:string,anchor:HTMLElement)=>{const s=state.value;const m=s.messages[s.selected]?.find(m=>m.id===id);openReactionPicker(anchor,{selected:m?.reaction?(m.emoji||'❤️'):undefined,onSelect:emoji=>react(id,emoji)});};
const button=(label:string,props:Record<string,unknown>={})=>h(Button,props,()=>label);
return()=>{const s=state.value;const room=s.conversations.find(c=>c.id===s.selected)||s.conversations[0];const allMessages=s.messages[room.id]||[];const messages=allMessages.filter(m=>!m.parentId);const parent=allMessages.find(m=>m.id===s.threadId);const threadMessages=parent?allMessages.filter(m=>m.parentId===parent.id):[];
return h(Theme,{mode:s.theme,class:'demo-root','data-compact':s.compact},()=>[
 h('div',{class:'demo-toolbar'},[h('div',{class:'demo-tools'},[h('a',{href:'./index.html'},'React'),h('a',{href:'./vue.html','aria-current':'page'},'Vue'),h('span',{class:'demo-local'},'Lokal demo')]),h('div',{class:'demo-tools'},[button(s.theme==='dark'?'Lyst':'Mørkt',{'aria-label':'Byt fargetema',onClick:()=>update({theme:s.theme==='dark'?'light':'dark'})}),button(s.compact?'Full breidd':'Vis smal',{'aria-label':'Smal førehandsvising','aria-pressed':s.compact,onClick:()=>update({compact:!s.compact})})])]),
 h('div',{class:'demo-surface'},[h(AppShell,{view:s.view},{header:()=>[h('span',{class:'sp-brand'},'Sprøyt.'),h('span',{class:'demo-local'},'Berre i nettlesaren din')],navigation:()=>[h(TextField,{label:'Finn ein samtale',type:'search',modelValue:s.query,'onUpdate:modelValue':(query:string)=>update({query}),placeholder:'Søk etter namn …'}),h(ConversationList,{items:s.conversations.filter(c=>(c.name+' '+c.group).toLocaleLowerCase().includes(s.query.toLocaleLowerCase())),selectedId:room.id,onSelect:(id:string)=>{nearBottom=true;select(id);}}),button('+ Ny samtale',{class:'demo-new',onClick:()=>{name.value='';error.value='';update({dialog:'new'});}})],default:()=>[h('div',{class:'sp-discussion','data-thread-open':!!parent},[h('section',{class:'sp-channel-pane','aria-label':'Samtale'},[
 h('header',{class:'sp-context'},[h('div',[h('div',{class:'sp-kicker'},room.group),h('h1',{class:'sp-heading'},room.name)]),h('div',{class:'sp-row'},[button('← Samtalar',{class:'sp-only-compact',onClick:()=>update({view:'list'})}),button(`Folk · ${s.people.length}`,{onClick:()=>update({dialog:'people',personQuery:''})})])]),
 h('div',{class:'sp-timeline',ref:timeline,onScroll:(e:Event)=>{const el=e.currentTarget as HTMLElement;nearBottom=el.scrollHeight-el.scrollTop-el.clientHeight<80;}},[h('div',{class:'sp-date sp-kicker'},'Samtalen'),!messages.length&&h('div',{class:'demo-empty'},[h('h2',{class:'sp-heading'},'Her byrjar samtalen.'),h('p','Skriv den første meldinga nedanfor.')]),...messages.map(m=>h(Message,{key:m.id,onReactionRequest:(anchor:HTMLElement)=>picker(m.id,anchor),author:m.author,time:m.time,status:m.status==='failed'?'Ikkje send':undefined},{default:()=>[m.reply&&h('div',{class:'demo-reply'},m.reply),m.body,m.image&&h('button',{type:'button',class:'demo-image-button','aria-label':'Opne bilete',onClick:()=>update({dialog:'image',image:m.image!})},h('img',{class:'demo-image',src:m.image,alt:m.imageName||'Vedlagt bilete'})),m.event&&h(EventCard,{title:'Middag på laurdag',when:'19. september · 18:00',where:'Hos Anne',modelValue:s.rsvp,'onUpdate:modelValue':(rsvp:Rsvp)=>update({rsvp}),summary:rsvpSummary(s.rsvp)}),allMessages.some(r=>r.parentId===m.id)&&h('button',{type:'button',class:'sp-thread-link','aria-expanded':s.threadId===m.id,onClick:()=>reply(m)},`${allMessages.filter(r=>r.parentId===m.id).length} svar · Opne tråd →`)],actions:()=>[button(m.reaction?(m.emoji||'❤️')+' 1':'♡',{variant:'quiet','aria-pressed':m.reaction,'aria-label':`Reager på meldinga frå ${m.author}`,onClick:(e:MouseEvent)=>picker(m.id,e.currentTarget as HTMLElement)}),button('Svar',{variant:'quiet',onClick:()=>reply(m)}),m.status==='failed'&&button('Prøv igjen',{variant:'danger',onClick:()=>retry(m.id)})]}))]),
 h('div',{class:'demo-notice',role:'status'},s.notice),
 h(Composer,{label:`Melding til ${room.name}`,modelValue:s.drafts[room.id]||'','onUpdate:modelValue':draft,onSend:send},{tools:()=>h('div',{class:'demo-attachment'},[button('+ Bilete',{variant:'quiet',onClick:()=>file.value?.click()}),h('label',{class:'demo-check'},[h('input',{type:'checkbox',checked:s.failNext,onChange:(e:Event)=>update({failNext:(e.target as HTMLInputElement).checked})}),'Test sendefeil'])]),leading:()=>[s.replies[room.id]&&h('div',{class:'demo-reply'},[h('span',s.replies[room.id]),button('×',{variant:'quiet','aria-label':'Avbryt svar',onClick:()=>update({replies:{...s.replies,[room.id]:''}})})]),s.images[room.id]?.data&&h('div',{class:'demo-attachment'},[h('span',s.images[room.id].name),button('Fjern',{variant:'quiet',onClick:()=>update({images:{...s.images,[room.id]:{data:'',name:''}}})})])]}),
 h('input',{class:'demo-file',ref:file,type:'file','aria-label':'Vel bilete',accept:'image/png,image/jpeg,image/webp,image/gif',onChange:(e:Event)=>{const input=e.target as HTMLInputElement;attach(input.files?.[0]);input.value='';}})
 ]),parent&&h(ThreadPane,{key:parent.id,context:room.name,title:'Tråd',onClose:closeThread},{parent:()=>h(Message,{author:parent.author,time:parent.time},()=>[parent.body,parent.event&&h('p',{class:'sp-help'},'Invitasjon · Middag på laurdag'),parent.image&&h('img',{class:'demo-image',src:parent.image,alt:parent.imageName||'Vedlagt bilete'})]),default:()=>[h('div',{class:'sp-date sp-kicker',role:'status'},`${threadMessages.length} svar`),!threadMessages.length&&h('p',{class:'sp-help'},'Svar her blir samla under denne meldinga.'),...threadMessages.map(m=>h(Message,{key:m.id,onReactionRequest:(anchor:HTMLElement)=>picker(m.id,anchor),author:m.author,time:m.time},{default:()=>m.body,actions:()=>button(m.reaction?(m.emoji||'❤️')+' 1':'♡',{variant:'quiet','aria-pressed':m.reaction,'aria-label':`Reager på svaret frå ${m.author}`,onClick:(e:MouseEvent)=>picker(m.id,e.currentTarget as HTMLElement)})}))],composer:()=>h(Composer,{label:`Svar i tråd til ${parent.author}`,placeholder:'Svar i denne tråden …',modelValue:s.threadDrafts[parent.id]||'','onUpdate:modelValue':threadDraft,onSend:sendThread})})]) ]})]),
 h(Dialog,{open:s.dialog==='people',title:`Folk i ${room.name}`,onClose:()=>update({dialog:null})},()=>[h(TextField,{label:'Finn ein person',type:'search',modelValue:s.personQuery,'onUpdate:modelValue':(personQuery:string)=>update({personQuery})}),h(PersonList,{people:s.people.filter(p=>p.name.toLocaleLowerCase().includes(s.personQuery.toLocaleLowerCase()))}),h('p',{class:'demo-caption'},'Illustrerande deltakarar. Demoen inviterer ingen.')]),
 h(Dialog,{open:s.dialog==='new',title:'Ny samtale',onClose:()=>update({dialog:null})},()=>h('form',{class:'sp-stack',onSubmit:(e:Event)=>{e.preventDefault();if(!name.value.trim()){error.value='Skriv eit namn.';return;}if(!createConversation(name.value))error.value='Du har allereie ein samtale med dette namnet.';}},[h(TextField,{label:'Namn på samtalen',modelValue:name.value,'onUpdate:modelValue':(v:string)=>{name.value=v;error.value='';},error:error.value,maxlength:80,autocomplete:'off'}),button('Opprett samtale',{type:'submit',variant:'primary'})])),
 h(Dialog,{open:s.dialog==='image',title:'Bilete',onClose:()=>update({dialog:null})},()=>s.image?h('img',{class:'demo-image-full',src:s.image,alt:'Vedlagt bilete i full storleik'}):null)
]);};}})).mount('#root');
