import type {Conversation,Person,Rsvp,ThemeMode} from '../../src/tokens';
export interface ChatMessage{id:string;author:string;body:string;time:string;reaction:boolean;emoji?:string;status?:'failed'|'sent';reply?:string;image?:string;imageName?:string;event?:boolean;parentId?:string}
export interface ChatState{theme:ThemeMode;compact:boolean;threadId:string|null;threadDrafts:Record<string,string>;selected:string;view:'list'|'detail';query:string;personQuery:string;dialog:null|'people'|'new'|'image';image:string;notice:string;failNext:boolean;conversations:Conversation[];messages:Record<string,ChatMessage[]>;drafts:Record<string,string>;replies:Record<string,string>;images:Record<string,{data:string;name:string}>;rsvp?:Rsvp;people:Person[]}
export const initialState=():ChatState=>({theme:'dark',compact:false,threadId:null,threadDrafts:{},selected:'walk',view:'detail',query:'',personQuery:'',dialog:null,image:'',notice:'',failNext:false,conversations:[{id:'walk',name:'Prat',group:'Mandagstur'},{id:'next',name:'Neste tur',group:'Mandagstur',unread:2},{id:'pictures',name:'Bilder',group:'Filosofene'},{id:'marine',name:'Maritim engineering',group:'Filosofene',muted:true},{id:'trip',name:'Utflukter',group:'Filosofene',unread:3},{id:'ferry',name:'Ferger',group:'Paros'},{id:'travel',name:'Reise',group:'Paros'}],messages:{walk:[{id:'a',author:'Anne',body:'Takk for turen! Skal vi samlast til middag på laurdag?',time:'16:42',reaction:false,event:true},{id:'b',author:'Lars',body:'Gjerne! Eg kan ta med noko til dessert.',time:'16:48',reaction:false},{id:'c',author:'Ingrid',body:'Det høyrest fint ut. Eg tek med brød!',time:'16:51',reaction:false}],next:[{id:'d',author:'Anne',body:'Kvar skal vi gå neste måndag? Eg foreslår ein tur langs sjøen.',time:'10:12',reaction:false}],trip:[{id:'e',author:'Lars',body:'Er det nokon som vil bli med på fjelltur i helga?',time:'09:30',reaction:false}]},drafts:{},replies:{},images:{},people:[{id:'anne',name:'Anne',detail:'Vert'},{id:'lars',name:'Lars',detail:'Medlem'},{id:'ingrid',name:'Ingrid',detail:'Medlem'},{id:'martin',name:'Martin',detail:'Medlem'},{id:'sofia',name:'Sofia',detail:'Medlem'},{id:'you',name:'Du',detail:'Medlem'}]});
let state=initialState();
try{const saved=JSON.parse(localStorage.getItem('sproyt-demo-v1')||'null');if(saved&&saved.version===1&&Array.isArray(saved.state?.conversations)&&saved.state.conversations.every((c:Conversation)=>typeof c.id==='string'&&typeof c.name==='string'&&typeof c.group==='string')&&saved.state.messages&&saved.state.drafts){state={...initialState(),...saved.state,dialog:null,view:'detail',notice:'',images:{},compact:false,threadId:null};}}catch{/* A blocked or full store must not stop the demo. */}
const listeners=new Set<()=>void>();
export const getState=()=>state;
export const subscribe=(listener:()=>void)=>{listeners.add(listener);return()=>{listeners.delete(listener);};};
export function update(patch:Partial<ChatState>){state={...state,...patch};try{localStorage.setItem('sproyt-demo-v1',JSON.stringify({version:1,state:{...state,images:{},messages:Object.fromEntries(Object.entries(state.messages).map(([id,items])=>[id,items.map(({image,imageName,...m})=>({...m,...(image?{body:m.body+' [Lokalt bilete blir ikkje lagra]'}:{})}))]))}}));}catch{/* In-memory use remains available. */}listeners.forEach(fn=>fn());}
export function select(id:string){if(!state.conversations.some(c=>c.id===id))return;update({selected:id,threadId:null,view:'detail',notice:'',conversations:state.conversations.map(c=>c.id===id?{...c,unread:0}:c)});}
export function draft(value:string){update({drafts:{...state.drafts,[state.selected]:value}});}
export function send(body:string){if(!body.trim())return;const id=state.selected;const attachment=state.images[id];const message:ChatMessage={id:crypto.randomUUID(),author:'Du',body:body.trim(),time:new Date().toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'}),reaction:false,status:state.failNext?'failed':'sent',reply:state.replies[id],image:attachment?.data,imageName:attachment?.name};update({messages:{...state.messages,[id]:[...(state.messages[id]||[]),message]},drafts:{...state.drafts,[id]:''},replies:{...state.replies,[id]:''},images:{...state.images,[id]:{data:'',name:''}},notice:state.failNext?'Meldinga vart ikkje send. Prøv igjen ved meldinga.':'Melding lagt til i demoen.',failNext:false});}
export function react(id:string,emoji='❤️'){update({messages:{...state.messages,[state.selected]:(state.messages[state.selected]||[]).map(m=>m.id===id?{...m,reaction:!(m.reaction&&(m.emoji||'❤️')===emoji),emoji}:m)}});}
export function retry(id:string){update({messages:{...state.messages,[state.selected]:(state.messages[state.selected]||[]).map(m=>m.id===id?{...m,status:'sent'}:m)},notice:'Meldinga er send i demoen.'});}
let threadTrigger:HTMLElement|null=null;
export function reply(m:ChatMessage){
 const root=m.parentId||m.id;
 if(!(state.messages[state.selected]||[]).some(item=>item.id===root&&!item.parentId))return;
 threadTrigger=typeof document!=='undefined'?document.activeElement as HTMLElement:null;
 update({threadId:root,view:'detail',notice:''});
 requestAnimationFrame(()=>document.querySelector<HTMLTextAreaElement>('.sp-thread-pane textarea')?.focus());
}
export function closeThread(){update({threadId:null});requestAnimationFrame(()=>{if(threadTrigger?.isConnected)threadTrigger.focus();});}
export function threadDraft(value:string){if(state.threadId)update({threadDrafts:{...state.threadDrafts,[state.threadId]:value}});}
export function sendThread(body:string){
 const parentId=state.threadId;const channel=state.selected;
 if(!body.trim()||!parentId||!(state.messages[channel]||[]).some(m=>m.id===parentId&&!m.parentId))return;
 const message:ChatMessage={id:crypto.randomUUID(),parentId,author:'Du',body:body.trim(),time:new Date().toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'}),reaction:false,status:'sent'};
 update({messages:{...state.messages,[channel]:[...(state.messages[channel]||[]),message]},threadDrafts:{...state.threadDrafts,[parentId]:''}});
 requestAnimationFrame(()=>{const list=document.querySelector('.sp-thread-replies');if(list)list.scrollTop=list.scrollHeight;});
}
export function createConversation(name:string){if(!name.trim())return false;const group='Mine samtalar';if(state.conversations.some(c=>c.group===group&&c.name.toLocaleLowerCase()===name.trim().toLocaleLowerCase()))return false;const id=crypto.randomUUID();update({conversations:[...state.conversations,{id,name:name.trim(),group}],messages:{...state.messages,[id]:[]},selected:id,threadId:null,dialog:null,view:'detail',notice:'Samtalen er oppretta lokalt.'});return true;}
export function attach(file?:File){if(!file)return;if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>2*1024*1024){update({notice:'Vel eit JPG-, PNG-, WebP- eller GIF-bilete under 2 MB.'});return;}const channel=state.selected;const reader=new FileReader();reader.onerror=()=>update({notice:'Biletet kunne ikkje lesast.'});reader.onload=()=>{update({images:{...state.images,[channel]:{data:String(reader.result),name:file.name}},notice:'Biletet er klart. Skriv ei kort melding og send.'});};reader.readAsDataURL(file);}
export function rsvpSummary(value?:Rsvp){return value?`Ditt svar: ${value==='yes'?'Eg kjem':value==='maybe'?'Kanskje':'Kan ikkje'} · ${value==='yes'?4:3} kjem`:'3 kjem · 2 har ikkje svart';}
