{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sproyt.fullname" . }}
  labels:
    {{- include "sproyt.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sproyt.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector: {}
        {{- with .Values.networkPolicy.ingressNamespaceSelector }}
        - namespaceSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 9010
  egress:
    - to:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.dnsNamespaceSelector | nindent 12 }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 443
    {{- if .Values.networkPolicy.databaseSameNamespace }}
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5432
    {{- end }}
    {{- with .Values.networkPolicy.databaseNamespaceSelector }}
    - to:
        - namespaceSelector:
            {{- toYaml . | nindent 12 }}
          {{- with $.Values.networkPolicy.databasePodSelector }}
          podSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      ports:
        - protocol: TCP
          port: 5432
    {{- end }}
    {{- range .Values.networkPolicy.databaseCidrs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
      ports:
        - protocol: TCP
          port: 5432
    {{- end }}
{{- end }}
